version: 2
updates:
  - package-ecosystem: github-actions
    directory: /
    schedule:
      interval: weekly
  - package-ecosystem: pip
    directory: /
    schedule:
      interval: weekly
  - package-ecosystem: terraform
    directory: /terraform/accounts/network
    schedule:
      interval: weekly
  - package-ecosystem: terraform
    directory: /terraform/accounts/dev
    schedule:
      interval: weekly
  - package-ecosystem: terraform
    directory: /terraform/accounts/sandbox
    schedule:
      interval: weekly
